repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v4.0.0-alpha.8"
      hooks:
          - id: prettier
    - repo: https://github.com/psf/black
      rev: 24.8.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
